const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {spawn}=require('node:child_process');
(async()=>{
 fs.mkdirSync('.preview',{recursive:true});fs.mkdirSync('test-results',{recursive:true});
 if(!fs.existsSync('.preview/ev-flexibility-twin'))fs.symlinkSync('../out','.preview/ev-flexibility-twin','dir');
 const server=spawn('python3',['-m','http.server','4173','--directory','.preview'],{stdio:'ignore'});
 let browser;
 try{
  for(let i=0;i<60;i++){try{const r=await fetch('http://127.0.0.1:4173/ev-flexibility-twin/');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}
  browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true});page.setDefaultTimeout(30000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/ev-flexibility-twin/',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'One site. A shared energy system.',exact:true}).waitFor();
  await page.getByRole('link',{name:'AI forecast controller',exact:true}).click();
  await page.getByLabel('Physical training days').selectOption('35');
  await page.getByRole('button',{name:'Train physical controller',exact:true}).click();
  await page.getByRole('heading',{name:'Fresh physical benchmark',exact:true}).waitFor({timeout:180000});
  const physicalDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export physical evidence',exact:true}).click();
  const physicalFile=await physicalDownload;const physical=JSON.parse(fs.readFileSync(await physicalFile.path(),'utf8'));assert.equal(physical.model.schema,'physical-forecast/1');assert.equal(physical.benchmark.seeds.length,3);assert.equal(physical.benchmark.totals.length,9);
  await page.getByLabel('Physical scenario').selectOption('1');
  await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=window.innerWidth);await page.screenshot({path:'test-results/physical-forecast-mobile.png',fullPage:true});
  await page.setViewportSize({width:1600,height:1000});await page.getByRole('link',{name:'Replay AI controller in 3D twin',exact:true}).click();
  await page.locator('tr[data-strategy="forecast"].selected-run').waitFor();assert.ok(await page.getByRole('switch',{name:'Enable AI forecast controller'}).isChecked());
  await page.getByRole('button',{name:'Replay Load balancing',exact:true}).click();await page.locator('tr[data-strategy="balanced"].selected-run').waitFor();
  await page.evaluate(()=>{localStorage.removeItem('ev-physical-forecast-v1');localStorage.removeItem('ev-physical-replay-v1');});await page.reload({waitUntil:'networkidle'});
  await page.goto('http://127.0.0.1:4173/ev-flexibility-twin/forecasting/',{waitUntil:'networkidle'});
  await page.getByLabel('Forecast dataset size').selectOption('35');
  await page.getByRole('button',{name:'Train demand forecast',exact:true}).click();
  await page.getByRole('heading',{name:'Unseen demand: paired results',exact:true}).waitFor({timeout:60000});
  const forecastDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export evidence',exact:true}).click();
  const forecastFile=await forecastDownload;const forecastEvidence=JSON.parse(fs.readFileSync(await forecastFile.path(),'utf8'));assert.equal(forecastEvidence.model.version,1);assert.equal(forecastEvidence.benchmark.days,35);assert.equal(forecastEvidence.benchmark.totals[1].violations,0);assert.equal(forecastEvidence.benchmark.summaries.length,3);assert.equal(forecastEvidence.benchmark.totals.length,6);assert.ok(forecastEvidence.model.controller);
  await page.getByLabel('Forecast capacity').selectOption('0.45');assert.ok((await page.locator('.flex-results').innerText()).includes('45%'));
  await page.screenshot({path:'test-results/demand-forecast-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=window.innerWidth);await page.screenshot({path:'test-results/demand-forecast-mobile.png',fullPage:true});
  await page.setViewportSize({width:1600,height:1000});await page.goto('http://127.0.0.1:4173/ev-flexibility-twin/',{waitUntil:'networkidle'});
  await page.getByRole('link',{name:'Strategy learning',exact:true}).click();
  await page.getByRole('heading',{name:'Learn when each strategy earns its place.',exact:true}).waitFor();
  await page.getByLabel('Selector dataset size').selectOption('35');
  await page.getByRole('button',{name:'Train across six strategies',exact:true}).click();
  await page.getByRole('heading',{name:'Held-out results: AI versus every fixed strategy',exact:true}).waitFor({timeout:180000});
  assert.equal(await page.locator('.selector-highlight').count(),1);
  const selectorDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export selector',exact:true}).click();
  const selectorFile=await selectorDownload;const selectorModel=JSON.parse(fs.readFileSync(await selectorFile.path(),'utf8'));assert.equal(selectorModel.schemaVersion,'ev-strategy-selector/2');assert.ok(selectorModel.examples.length>0);
  await page.screenshot({path:'test-results/strategy-learning-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.documentElement.scrollWidth<=window.innerWidth);
  await page.screenshot({path:'test-results/strategy-learning-mobile.png',fullPage:true});
  await page.setViewportSize({width:1600,height:1000});
  await page.getByRole('link',{name:'Replay with learned selection',exact:true}).click();
  assert.ok(await page.getByRole('switch',{name:'Use learned strategy selector'}).isChecked());
  assert.ok((await page.locator('.flex-results').innerText()).includes('neighbour label agreement'));
  await page.getByRole('button',{name:'Reset to depot example',exact:true}).click();
  await page.getByRole('link',{name:'EMS simulator',exact:true}).click();

  await page.getByRole('link',{name:'Flexibility markets',exact:true}).click();
  await page.getByRole('heading',{name:'Can your charging pool deliver its promise?',exact:true}).waitFor();
  assert.ok((await page.locator('.flex-metrics').innerText()).includes('Accepted'));
  await page.getByLabel('Requested grid connection',{exact:true}).fill('OTHER');
  assert.ok((await page.locator('.flex-metrics').innerText()).includes('Rejected'));
  await page.getByLabel('Requested grid connection',{exact:true}).fill('NL-DEPOT-A');
  const flexDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export evidence'}).click();
  const flexFile=await flexDownload;const flexJson=JSON.parse(fs.readFileSync(await flexFile.path(),'utf8'));assert.equal(flexJson.reference.schemaVersion,'ev-flexibility-report/1');
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.documentElement.scrollWidth<=window.innerWidth);
  await page.screenshot({path:'test-results/flexibility-mobile.png',fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.setViewportSize({width:1600,height:1000});await page.goto('http://127.0.0.1:4173/ev-flexibility-twin/',{waitUntil:'networkidle'});

  await page.getByRole('button',{name:'Compare strategies',exact:true}).click();
  await page.getByRole('heading',{name:'Six strategies. One set of assumptions.',exact:true}).waitFor();
  assert.equal(await page.locator('tr[data-strategy]').count(),6);
  const reference=await page.locator('tr[data-strategy="balanced"] td').allTextContents();
  const names=[['immediate','Immediate charging'],['balanced','Load balancing'],['ems','Deadline-aware EMS'],['cheap','Cheapest energy'],['peak','Peak-aware'],['total','Total-cost-aware']];
  for(const [id,name] of names){
   await page.getByRole('button',{name:`Replay ${name}`,exact:true}).click();
   await page.locator(`tr[data-strategy="${id}"].selected-run`).waitFor();
   assert.ok((await page.locator('.scene-sub').innerText()).includes(name));
   assert.deepEqual(await page.locator('tr[data-strategy="balanced"] td').allTextContents(),reference);
  }
  console.log('PASS: six replays update the twin; baseline metrics remain unchanged.');
  await page.getByLabel('Comparison chart metric',{exact:true}).selectOption('cost');
  await page.getByLabel('Comparison chart metric',{exact:true}).selectOption('energy');
  const csvPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Comparison CSV',exact:true}).click();const csv=fs.readFileSync(await (await csvPromise).path(),'utf8');assert.equal(csv.split('\n').length,7);assert.ok(csv.includes('"EUR"'));assert.ok(!csv.includes('£'));
  const jsonPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Evidence JSON',exact:true}).click();const evidence=JSON.parse(fs.readFileSync(await (await jsonPromise).path(),'utf8'));assert.equal(evidence.results.length,6);assert.equal(evidence.assumptions.currency,'EUR');
  const scenarioPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export scenario',exact:true}).click();const scenario=JSON.parse(fs.readFileSync(await (await scenarioPromise).path(),'utf8'));assert.equal(scenario.schemaVersion,2);assert.equal(scenario.optimizer.policy,'total');assert.equal(scenario.advanced,true);
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Replay Immediate charging',exact:true}).click();await page.getByRole('button',{name:'Restore',exact:true}).click();await page.locator('tr[data-strategy="total"].selected-run').waitFor();
  console.log('PASS: EUR CSV, evidence JSON, scenario export and browser restore.');
  const oldId=await page.locator('.compare-intro .eyebrow').innerText();
  await page.getByRole('combobox',{name:'Market profile',exact:true}).click();await page.getByRole('option',{name:'Wallonia',exact:true}).click();
  await page.waitForFunction(old=>document.querySelector('.compare-intro .eyebrow')?.textContent!==old,oldId);
  assert.ok((await page.locator('.compare-assumptions').innerText()).includes('Wallonia'));
  const energyBefore=await page.locator('tr[data-strategy="total"] td').first().innerText();
  await page.locator('.comparison-method summary').click();await page.getByLabel('Monthly capacity rate',{exact:true}).fill('4.45');
  assert.equal(await page.locator('tr[data-strategy="total"] td').first().innerText(),energyBefore);
  console.log('PASS: tariff setting shared; monthly sensitivity not added to daily energy cost.');
  await page.getByRole('combobox',{name:'Timeline chart view',exact:true}).click();await page.getByRole('option',{name:'Compare regions',exact:true}).click();
  assert.equal(await page.locator('.main-grid .chart-panel .recharts-line').count(),4);assert.ok((await page.locator('.main-grid .chart-panel').innerText()).includes('not supplier tariffs'));
  await page.getByRole('combobox',{name:'Timeline chart view',exact:true}).click();await page.getByRole('option',{name:'Environment',exact:true}).click();
  assert.equal(await page.locator('.main-grid .chart-panel .recharts-line').count(),2);assert.ok((await page.locator('.main-grid .chart-panel').innerText()).includes('humidity, wind and precipitation are not modeled'));
  console.log('PASS: shared timeline switches to four synthetic regional tariffs and time-varying environment inputs.');
  await page.locator('.strategy-analysis').screenshot({path:'test-results/comparison-desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Replay Peak-aware',exact:true}).click();await page.locator('tr[data-strategy="peak"].selected-run').waitFor();
  await page.screenshot({path:'test-results/comparison-mobile.png',fullPage:true});
  await page.getByRole('tab',{name:'EMS control loop'}).click();
  await page.getByRole('heading',{name:'EMS control loop · 08:45',exact:true}).waitFor();
  assert.equal(await page.locator('.ems-trace-row').count(),6);
  assert.ok((await page.locator('.ems-notice').innerText()).includes('no external feed or OCPP wire adapter is connected'));
  await page.getByRole('combobox',{name:'Scenario'}).click();
  await page.getByRole('option',{name:'EMS connection lost',exact:true}).click();
  const timeSlider=page.getByLabel('Simulation time in minutes').locator('[role="slider"]');for(let i=0;i<85;i++)await timeSlider.press('ArrowRight');
  await page.getByRole('heading',{name:'EMS control loop · 10:10',exact:true}).waitFor();
  assert.ok((await page.locator('.ems-trace-row').nth(3).innerText()).includes('No remote command sent'));
  assert.ok((await page.locator('.ems-trace-row').nth(5).innerText()).toLowerCase().includes('fallback recorded'));
  console.log('PASS: selected simulation time exposes the EMS trace and offline local-fallback path.');
  await page.goto('http://127.0.0.1:4173/ev-flexibility-twin/training/',{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Backtest one synthetic year, then train.',exact:true}).waitFor();
  assert.ok((await page.locator('.synthetic-warning').innerText()).includes('Illustrative results from synthetic data'));
  assert.equal(await page.locator('.training-flow-steps article').count(),4);
  assert.ok((await page.locator('.training-flow-storage').innerText()).includes('not uploaded to GitHub'));
  assert.equal(await page.getByRole('button',{name:'Train on this backtest',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Run 365-day backtest',exact:true}).waitFor();
  const model={schemaVersion:1,algorithm:'compact-mlp-v1',createdAt:'2026-01-01T00:00:00Z',teacherPolicy:'ems',market:'nl',days:365,rowCount:1000,trainRows:600,validationRows:200,testRows:200,features:['minute_sin','minute_cos','year_sin','year_cos','outdoor_c','irradiance','tariff_eur_kwh','building_kw','headroom_ratio','battery_soc','vehicle_soc','energy_remaining_ratio','departure_slack_min','driver_group','flexible_loads','charger_kw','battery_enabled'],hiddenUnits:2,weightsInputHidden:new Array(34).fill(0),biasHidden:[0,0],weightsHiddenOutput:[0,0],biasOutput:0,epochs:2,seed:1,metrics:{trainMae:.1,validationMae:.11,testMae:.12,testRmse:.2,testActionAgreement:.8},datasetFingerprint:'browser-fixture'};
  await page.locator('input[type=file]').setInputFiles({name:'synthetic-model.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(model))});
  await page.getByText('Model package imported and made available to the Energy Twin.',{exact:true}).waitFor();
  await page.screenshot({path:'test-results/ml-training-lab.png',fullPage:true});
  await page.getByRole('link',{name:'Apply in current DES',exact:true}).click();
  const learnedSwitch=page.getByRole('switch',{name:'Enable trained ML policy',exact:true});await learnedSwitch.waitFor();await learnedSwitch.click();
  await page.locator('tr[data-strategy="ml"].selected-run').waitFor();
  assert.equal(await page.locator('tr[data-strategy]').count(),7);
  assert.ok((await page.locator('.scene-sub').innerText()).includes('Learned EMS policy'));
  console.log('PASS: training route labels its synthetic data; imported model loads into the twin as a seventh safety-limited run.');
  await page.getByRole('link',{name:'Development roadmap',exact:true}).click();
  await page.getByRole('heading',{name:'From a replayable twin to a closed-loop EMS.',exact:true}).waitFor();
  assert.equal(await page.locator('.roadmap-phase').count(),7);
  assert.equal(await page.locator('.roadmap-phase[data-status="prototype"]').count(),4);
  assert.ok((await page.locator('.roadmap-scope-note').innerText()).includes('not connected to live'));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,'Roadmap fits the mobile viewport without horizontal overflow');
  await page.screenshot({path:'test-results/roadmap-mobile.png',fullPage:true});
  await page.getByRole('link',{name:'Run synthetic replay',exact:true}).click();
  await page.getByRole('heading',{name:'One trace, end to end.',exact:true}).waitFor();
  await page.getByRole('combobox',{name:'Virtual charger response',exact:true}).selectOption('missing');
  await page.getByRole('button',{name:'Run deterministic replay',exact:true}).click();
  await page.getByText('acknowledgement missing',{exact:true}).waitFor();
  assert.ok((await page.locator('.replay-reconcile-list').innerText()).includes('ack unknown'));
  await page.getByRole('combobox',{name:'Scenario fixture',exact:true}).selectOption('connection-loss');
  await page.getByRole('button',{name:'Run deterministic replay',exact:true}).click();
  await page.getByText('withheld · local fallback',{exact:true}).waitFor();
  assert.ok((await page.locator('.replay-outcome-grid').innerText()).includes('Link restored'));
  await page.getByRole('combobox',{name:'Scenario fixture',exact:true}).selectOption('grid-limit');
  await page.getByRole('combobox',{name:'Meter telemetry',exact:true}).selectOption('stale');
  await page.getByRole('button',{name:'Run deterministic replay',exact:true}).click();
  assert.ok((await page.locator('.replay-reconcile-list').innerText()).includes('feedback stale'));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,'Replay lab fits the mobile viewport without horizontal overflow');
  await page.screenshot({path:'test-results/replay-lab-mobile.png',fullPage:true});
  assert.deepEqual(errors,[],'No uncaught browser errors');
  console.log('PASS: roadmap links to the deterministic replay lab; missing acknowledgement and local fallback are inspectable on mobile.');
 }finally{if(browser)await browser.close();server.kill();}
})().catch(error=>{console.error(error);process.exitCode=1;});
