'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Zap,BrainCircuit,Download,ArrowLeft,History} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend,CartesianGrid} from 'recharts';
import {flexDefaults,products,runFlexibility,type FlexOptions} from '../../lib/twin/flexibility';
import {isNetwork,ML_MODEL_STORAGE_KEY,type Network} from '../../lib/twin/ml';
import {Switch} from '../ui/switch';
import {SELECTOR_KEY,isSelector,predictStrategy,selectorInput,type SelectorModel,type Scenario} from '../../lib/twin/selector';
import {defaults} from '../../lib/twin/engine';
import {optimizerDefaults} from '../../lib/twin/optimizer';
import './FlexibilityLab.css';
export default function FlexibilityLab(){
 const [options,setOptions]=useState<FlexOptions>(flexDefaults),[model,setModel]=useState<Network>(),[useAI,setUseAI]=useState(false),[error,setError]=useState(''),[selector,setSelector]=useState<SelectorModel>(),[useSelector,setUseSelector]=useState(false),[source,setSource]=useState<Scenario>();
 useEffect(()=>{try{const raw=localStorage.getItem(ML_MODEL_STORAGE_KEY);if(raw){const n=JSON.parse(raw);if(isNetwork(n))setModel(n);}}catch{setError('Stored model could not be loaded. Train or import a valid model.');}},[]);
 useEffect(()=>{try{const saved=localStorage.getItem(SELECTOR_KEY);if(saved){const m=JSON.parse(saved);if(isSelector(m))setSelector(m);}const raw=localStorage.getItem('ev-selector-scenario-v1');if(raw){const scenario=JSON.parse(raw) as Scenario;runFlexibility(scenario.flex,undefined,'ems',scenario.config,scenario.optimizer);setSource(scenario);setOptions(scenario.flex);setUseSelector(true);localStorage.removeItem('ev-selector-scenario-v1');}}catch{setError('Invalid selector or replay scenario.');}},[]);
 const scenario:Scenario={config:source?.config??{...defaults,preset:'article',grid:250,solar:0,seed:options.seed},optimizer:source?.optimizer??optimizerDefaults,flex:options};
 const selection=selector?predictStrategy(selector,selectorInput(scenario)):undefined;
 const selectedReport=useMemo(()=>selector&&selection?runFlexibility(options,undefined,selection.strategy,source?{...source.config,seed:options.seed}:undefined,source?.optimizer):undefined,[options,selector,selection?.strategy,source]);
 const reference=useMemo(()=>runFlexibility(options,undefined,'ems',source?{...source.config,seed:options.seed}:undefined,source?.optimizer),[options,source]);
 const learned=useMemo(()=>model?runFlexibility(options,model,'ems',source?{...source.config,seed:options.seed}:undefined,source?.optimizer):undefined,[options,model,source]);
 const report=useSelector&&selectedReport?selectedReport:useAI&&learned?learned:reference;
 function change<K extends keyof FlexOptions>(key:K,value:FlexOptions[K]){setOptions(p=>({...p,[key]:value}));}
 const number=(key:keyof FlexOptions,label:string,min:number,max:number,step=1)=><label>{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={Number(options[key])} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=min&&n<=max)change(key,n as never);}}/></label>;
 function exportReport(){const url=URL.createObjectURL(new Blob([JSON.stringify({reference,learned:learned??null,selected:selectedReport??null,selector:selector?{fingerprint:selector.fingerprint,selection}:null},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ev-flexibility-report-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className="flex-lab"><header className="header"><div className="brand"><div className="brandmark"><Zap size={23} fill="currentColor"/></div><div className="brandname">FUTURE <span>EV</span></div><div className="divider"/><h2>Flexibility Lab</h2></div><nav className="header-actions"><Link className="btn" href="/"><ArrowLeft size={17}/>EMS simulator</Link><Link className="btn" href="/strategy-training/"><BrainCircuit size={17}/>Strategy learning</Link><Link className="btn" href="/training/"><BrainCircuit size={17}/>AI training</Link><Link className="btn" href="/replay/"><History size={17}/>Replay lab</Link><button className="btn primary" onClick={exportReport}><Download size={17}/>Export evidence</button></nav></header><div className="workspace"><div className="intro"><div><p className="eyebrow">SMART BUILDING / MOBILITY / FLEXIBILITY</p><h1>Can your charging pool deliver its promise?</h1><p>Forecast → commitment → activation → evidence → settlement</p></div><span className="badge">Synthetic depot · virtual market</span></div>
 <aside className="flex-notice">Educational simulation on synthetic data. Product thresholds and prices are configurable illustrative assumptions, not verified market rules or qualification. No ChargeWeave or live operator connection.</aside>
 <div className="flex-layout"><section className="flex-card flex-controls"><h2>Configure the commitment</h2><label>Market product<select value={options.product} onChange={e=>{const p=products.find(p=>p.id===e.target.value)!;setOptions(o=>({...o,product:p.id,duration:p.durationMinutes,requestKw:p.minimumKw||100}));}}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p>{report.product.description}</p>
 {number('poolSites','Identical depots in pool',1,100)}{number('seed','Scenario seed',0,100000)}{number('start','Activation start (minute of day)',0,1200)}{number('duration','Duration (minutes)',1,240)}{number('requestKw','Requested reduction (kW)',0,20000)}{number('consent','Participating driver share',0,1,.1)}{number('latencySeconds','Control latency (seconds)',0,1800,10)}{number('reservedKw','Already committed elsewhere (kW)',0,20000)}{number('baselineBias','Settlement baseline bias (fraction)',-.5,.5,.01)}
 <label>Unexpected event<select value={options.failure} onChange={e=>change('failure',e.target.value as FlexOptions['failure'])}><option value="none">None</option><option value="fault">Two chargers fail</option><option value="offline">Remote control fails</option><option value="early">Four drivers leave early</option></select></label>
 <label>Pool grid connection<input value={options.connection} onChange={e=>change('connection',e.target.value||' ')} /></label><label>Requested grid connection<input value={options.requestedConnection} onChange={e=>change('requestedConnection',e.target.value||' ')} /></label>
 <label className="flex-check"><Switch aria-label="Virtual qualification granted" checked={options.qualified} onCheckedChange={v=>change('qualified',v)}/>Virtual qualification granted</label><label className="flex-check"><Switch aria-label="Local frequency measurement available" checked={options.edge} onCheckedChange={v=>change('edge',v)}/>Local frequency measurement available</label>
 <h3>Illustrative economics</h3>{number('capacityPrice','Capacity (€ / MW / hour)',0,10000)}{number('energyPrice','Delivery (€ / MWh)',0,10000)}{number('penaltyPrice','Shortfall (€ / MWh)',0,10000)}{number('aggregatorFee','Aggregator fee (fraction)',0,1,.01)}
 </section><div className="flex-results"><section className="flex-card"><div className="flex-title"><h2>Availability & eligibility</h2><label className="flex-check"><Switch aria-label="Use trained AI" disabled={!model} checked={useAI} onCheckedChange={v=>{setUseAI(v);if(v)setUseSelector(false);}}/>Use trained AI</label></div><p>{model?`Actual compact MLP loaded · ${model.teacherPolicy} teacher · ${model.datasetFingerprint}`:'No trained model loaded. Train one in the standalone AI lab or import a model package below.'}</p><input aria-label="Import AI model" type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const n=JSON.parse(await f.text());if(!isNetwork(n))throw Error('Invalid model package');setModel(n);localStorage.setItem(ML_MODEL_STORAGE_KEY,JSON.stringify(n));setError('');}catch(err){setError(String(err));}}}/>{error&&<p role="alert">{error}</p>}
 <div className="flex-title"><h3>Learned strategy selection</h3><label className="flex-check"><Switch aria-label="Use learned strategy selector" disabled={!selector} checked={useSelector} onCheckedChange={v=>{setUseSelector(v);if(v)setUseAI(false);}}/>Use learned selector</label></div><p>{selection?`Selected ${selection.strategy} · neighbour label agreement ${(selection.voteShare*100).toFixed(1)}% · nearest standardized distance ${selection.nearestDistance.toFixed(2)}. Cost-sensitive decision; ${selection.fallback?'validation-selected fallback':'estimated cost advantage'}. Agreement is not calibrated confidence.`:'Train across all six strategies in the Strategy Learning lab.'}</p>{selection&&<div className="flex-table"><table><thead><tr><th>Strategy</th><th>Estimated regret per depot ↓</th></tr></thead><tbody>{['immediate','balanced','ems','cheap','peak','total'].map((id,i)=><tr key={id}><th>{id}{id===selection.strategy?' · selected':''}</th><td>{selection.estimatedCosts[i].toFixed(2)}</td></tr>)}</tbody></table></div>}{source&&<p>Replay scenario: day {(source.config.dayOfYear??0)+1} · {source.config.preset} · {source.config.grid} kW grid · {source.config.solar} kWp solar · {source.optimizer.market}. <button className="btn" onClick={()=>{setSource(undefined);setOptions(flexDefaults);setUseSelector(false);}}>Reset to depot example</button></p>}
 <div className="flex-metrics"><div><small>Dependable reduction</small><b>{report.availableKw.toFixed(1)} kW</b></div><div><small>Increase headroom</small><b>{report.increaseKw.toFixed(1)} kW</b></div><div><small>Commitment</small><b>{report.accepted?'Accepted':options.product==='tariff'?'Implicit':'Rejected'}</b></div><div><small>Net simulated value</small><b>€{report.settlement.netValue.toFixed(2)}</b></div></div>{report.reasons.length>0&&<ul>{report.reasons.map(r=><li key={r}>{r}</li>)}</ul>}<p>Pool uses identical depot replicas at the selected connection; it does not imply geographic diversity. Reserved capacity is deducted before bidding. Charging MLP imitates one teacher; the separate learned selector chooses among all six strategies. Neither predicts plug-in probability.</p></section>
 <section className="flex-card"><h2>Activation delivery</h2>{report.metrics.violationMinutes>0&&<p role="status">Import capacity is exceeded during {report.metrics.violationMinutes} simulated minutes. Inspect site demand and strategy safety before interpreting costs or commitments.</p>}<div className="flex-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={report.evidence}><CartesianGrid stroke="#293644" strokeDasharray="3 3"/><XAxis dataKey="minute" tickFormatter={m=>`${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`}/><YAxis unit=" kW"/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:6,color:"var(--foreground)"}}/><Legend/><Line dataKey="baselineKw" name="Counterfactual grid load" stroke="#91a7fc" dot={false}/><Line dataKey="actualKw" name="Actual grid load" stroke="#70e3bb" dot={false}/><Line dataKey="requestedKw" name="Committed reduction" stroke="#66c1e8" dot={false}/><Line dataKey="deliveredKw" name="Assessed reduction" stroke="#f6c66b" dot={false}/></LineChart></ResponsiveContainer></div><p>Metering resolution: 60 seconds. FCR remains ineligible here even with edge measurement enabled. Baseline bias can change assessed delivery without changing physical charging.</p></section>
 <section className="flex-card"><h2>Charging MLP versus EMS · identical exogenous conditions</h2><div className="flex-table"><table><thead><tr><th>Measure</th><th>Deadline-aware EMS</th><th>Trained ML</th></tr></thead><tbody>{[['Commitment',reference.accepted?'Accepted':'Not accepted',learned?(learned.accepted?'Accepted':'Not accepted'):'Train model'],['Available kW',reference.availableKw,learned?.availableKw],['Delivered kWh',reference.metrics.deliveredKwh,learned?.metrics.deliveredKwh],['Delivery shortfall kWh',reference.metrics.shortfallKwh,learned?.metrics.shortfallKwh],['Departure shortfall kWh',reference.metrics.departureShortfallKwh,learned?.metrics.departureShortfallKwh],['Net value €',reference.settlement.netValue,learned?.settlement.netValue]].map(([name,a,b])=><tr key={String(name)}><th>{name}</th><td>{a}</td><td>{b??'—'}</td></tr>)}</tbody></table></div><p>Each policy freezes its own no-activation counterfactual. This measures end-to-end policy behaviour; accepted commitment volumes can differ.</p></section>
 <section className="flex-card"><h2>Settlement & audit trail</h2><div className="flex-table"><table><tbody>{Object.entries(report.settlement).map(([k,v])=><tr key={k}><th>{k.replace(/([A-Z])/g,' $1')}</th><td>€{v.toFixed(3)}</td></tr>)}</tbody></table></div><ol>{report.audit.map(a=><li key={a.state}><b>{a.state}</b> · minute {a.minute}<p>{a.detail}</p></li>)}</ol></section>
 <section className="flex-card"><h2>Market access map</h2><p>CPO controls charging infrastructure; eMSP handles mobility services and may have delegated control. Supplier/BRP carries energy balance; BSP provides qualified balancing services; CSP arranges local congestion flexibility. A virtual aggregator bridges the pool and these roles.</p><div className="flex-table"><table><thead><tr><th>Profile</th><th>Access role</th><th>Minimum kW*</th><th>Response*</th><th>Endurance*</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><th>{p.name}</th><td>{p.role}</td><td>{p.minimumKw}</td><td>{p.responseSeconds}s</td><td>{p.durationMinutes} min</td></tr>)}</tbody></table></div><p>*Illustrative profiles. Capacity block obligations, live prequalification, exchange access and official baseline methods require further market-specific implementation.</p></section></div></div></div></main>;
}
