"use client";
import {useMemo,useState} from 'react';
import {Download,ArrowUpRight,GitCompareArrows} from 'lucide-react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {clock} from '@/lib/twin/engine';
import {markets,type OptimizerConfig} from '@/lib/twin/optimizer';
import {comparisonCsv,exportComparison,type Comparison,type StrategyId} from '@/lib/twin/comparison';
import './StrategyComparison.css';
const n=(v:number,d=1)=>v.toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const euro=(v:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(v);
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type Props={comparison:Comparison;selected:StrategyId;onSelect:(id:StrategyId)=>void;onSettings:(patch:Partial<OptimizerConfig>)=>void};
export default function StrategyComparison({comparison:c,selected,onSelect,onSettings}:Props){
 const [plot,setPlot]=useState<'grid'|'energy'|'cost'>('grid');
 const active=c.runs.find(r=>r.id===selected)!,base=c.runs.find(r=>r.id==='balanced')!;
 const difference=base.metrics.energyCost-active.metrics.energyCost;
 const chart=useMemo(()=>Array.from({length:96},(_,q)=>{
  const a=active.result.frames.slice(q*15,q*15+15),b=base.result.frames.slice(q*15,q*15+15);
  const value=(frames:typeof a)=>plot==='grid'?frames.reduce((sum,f)=>sum+Math.max(0,f.grid),0)/15:plot==='energy'?frames[14].delivered:frames[14].cost;
  return {time:plot==='grid'?q*15:q*15+14,selected:value(a),reference:value(b),limit:Math.min(...a.map(f=>f.limit))};
 }),[active,base,plot]);
 const unit=plot==='grid'?'kW':plot==='energy'?'kWh':'€';
 return <div className="strategy-analysis">
  <div className="panel panel-body compare-intro">
   <div><div className="eyebrow">CONTROLLED EXPERIMENT · {c.fingerprint}</div><h2>{c.runs.length>6?'Six baselines plus learned controllers. Same assumptions.':'Six strategies. One set of assumptions.'}</h2><p>Each row is a separate run. Replay any row in the same 3D campus; the learned run uses the saved synthetic-data model and shares the same physical limits.</p></div>
   <div className="compare-actions"><button className="btn" onClick={()=>download(`strategy-comparison-${c.fingerprint}.csv`,comparisonCsv(c),'text/csv;charset=utf-8')}><Download/>Comparison CSV</button><button className="btn" onClick={()=>download(`strategy-evidence-${c.fingerprint}.json`,exportComparison(c),'application/json')}><Download/>Evidence JSON</button></div>
   <div className="compare-assumptions"><span>{c.runs[0].result.vehicles.length} visits · seed {c.config.seed}</span><span>{c.config.chargers} chargers</span><span>{c.config.grid} kW connection</span><span>{c.config.solar} kWp solar</span><span>Battery {c.config.battery?'on · 50 kWh start':'off'}</span><span>{markets.find(m=>m.id===c.optimizer.market)?.name} · synthetic weekday</span><span>EUR · excluding VAT</span></div>
  </div>
  <div className="panel comparison-table-panel"><div className="table-wrap"><table className="data-table comparison-table"><caption>Full-day site results. Lower cost alone does not establish a better outcome.</caption><thead><tr><th scope="col">Strategy</th><th scope="col">Energy cost<br/>€/24h</th><th scope="col">Ready<br/>vehicles</th><th scope="col">Delivered<br/>kWh</th><th scope="col">Shortfall<br/>kWh</th><th scope="col">Peak 1 min<br/>kW</th><th scope="col">Peak 15 min<br/>kW</th><th scope="col">Over limit<br/>minutes</th><th scope="col">Explore</th></tr></thead><tbody>{c.runs.map(r=><tr key={r.id} data-strategy={r.id} className={r.id===selected?'selected-run':''} aria-selected={r.id===selected}><th scope="row"><b>{r.name}</b><small>{r.id==='balanced'?'Comparison reference':r.id==='immediate'?'Uncontrolled baseline':r.id===selected?'Selected in the twin':''}</small></th><td>{euro(r.metrics.energyCost)}</td><td className={r.metrics.ready<r.metrics.departed?'amber':'green'}>{r.metrics.ready} / {r.metrics.departed}</td><td>{n(r.metrics.deliveredKwh)}</td><td className={r.metrics.shortfallKwh>.05?'amber':''}>{n(r.metrics.shortfallKwh)}</td><td>{n(r.metrics.minutePeakKw)}</td><td>{n(r.metrics.quarterPeakKw)}</td><td className={r.metrics.violationMinutes?'red':'green'}>{r.metrics.violationMinutes}</td><td><button className={`btn ${r.id===selected?'primary':''}`} aria-label={`Replay ${r.name}`} aria-pressed={r.id===selected} onClick={()=>onSelect(r.id)}>Replay <ArrowUpRight/></button></td></tr>)}</tbody></table></div></div>
  <div className="comparison-detail-grid">
   <div className="panel panel-body"><div className="eyebrow">SELECTED VS LOAD BALANCING</div><h2>{active.name}</h2><p className="scenario-note">{active.description}</p><div className="comparison-delta"><span>{active.equivalentService?'Energy spend reduction':'Energy spend difference'}</span><b>{euro(difference)}</b><small>Positive = less spent. Negative = more spent. Daily site energy only.</small></div><div className={`reason ${active.equivalentService?'':'comparison-caution'}`}>{active.comparisonNote}</div><div className="inspector-stat"><span>Import expenditure</span><b>{euro(active.metrics.importCost)}</b></div><div className="inspector-stat"><span>Export credit</span><b>{euro(active.metrics.exportCredit)}</b></div><div className="inspector-stat"><span>Requested vehicle energy</span><b>{n(active.metrics.requestedKwh)} kWh</b></div><div className="inspector-stat"><span>Energy above import limit</span><b>{n(active.metrics.excessKwh)} kWh</b></div>{c.config.battery&&<div className="inspector-stat"><span>Battery at day end / reference</span><b>{n(active.metrics.batteryEndKwh)} / {n(base.metrics.batteryEndKwh)} kWh</b></div>}</div>
   <div className="panel chart-panel"><div className="chart-header"><div><h2><GitCompareArrows size={18}/> Compare the trajectories</h2><small>{plot==='grid'?'Quarter-hour average import; export excluded.':plot==='energy'?'Cumulative energy delivered to vehicle batteries.':'Cumulative net site energy expenditure; excluding capacity charges.'}</small></div><select className="btn" value={plot} aria-label="Comparison chart metric" onChange={e=>setPlot(e.target.value as typeof plot)}><option value="grid">Import · kW</option><option value="energy">Delivered · kWh</option><option value="cost">Energy spend · €</option></select></div><div className="chart" style={{height:260,minWidth:0}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid stroke="#263844" vertical={false}/><XAxis dataKey="time" type="number" domain={[0,1439]} ticks={[0,360,720,1080,1439]} tickFormatter={clock}/><YAxis width={58} label={{value:unit,position:'insideTopLeft'}}/><Tooltip contentStyle={{background:'#14232f',border:'1px solid #3a5060'}} labelFormatter={v=>clock(Number(v))}/><Line isAnimationActive={false} type="stepAfter" dataKey="reference" name="Load balancing" stroke="#91a7fc" dot={false} strokeWidth={2} strokeDasharray="5 3"/><Line isAnimationActive={false} type="stepAfter" dataKey="selected" name={active.name} stroke="#70e3bb" dot={false} strokeWidth={2}/>{plot==='grid'&&<Line isAnimationActive={false} type="stepAfter" dataKey="limit" name="Import allowance" stroke="#f68b81" dot={false} strokeDasharray="3 3"/>}</LineChart></ResponsiveContainer></div><div className="legend"><span><i style={{background:'#70e3bb'}}/>{active.name}</span><span><i style={{background:'#91a7fc'}}/>Load balancing</span>{plot==='grid'&&<span><i style={{background:'#f68b81'}}/>Import allowance</span>}</div></div>
  </div>
  <details className="panel panel-body comparison-method"><summary>Peak-charge sensitivity and comparison method</summary><p>Preferred peak is a scheduling target, not a billable baseline. Enter your own illustrative capacity rate to estimate the extra monthly exposure caused by this day. This estimate is never added to daily energy expenditure. Zero rate means not modeled.</p><div className="comparison-inputs"><label>Existing monthly peak (kW)<input aria-label="Existing monthly peak" type="number" min={0} max={1000} step={1} value={c.optimizer.existingMonthlyPeakKw??85} onChange={e=>onSettings({existingMonthlyPeakKw:Math.max(0,Math.min(1000,Number(e.target.value)||0))})}/></label><label>Illustrative rate (€/kW/month)<input aria-label="Monthly capacity rate" type="number" min={0} max={100} step={.01} value={c.optimizer.capacityRateEurPerKwMonth??0} onChange={e=>onSettings({capacityRateEurPerKwMonth:Math.max(0,Math.min(100,Number(e.target.value)||0))})}/></label><div><span>Selected: incremental monthly exposure</span><strong>{active.metrics.incrementalMonthlyPeakCharge===null?'Not modeled':euro(active.metrics.incrementalMonthlyPeakCharge)}</strong></div></div><p>Calculated as max(0, this day’s highest quarter-hour average import − existing monthly peak) × entered monthly rate. A simplified sensitivity calculation, not a regulated tariff or an invoice. No fixed charges, tariff floors, rolling-year averaging or settlement are modeled.</p><p>All strategies share the same minute-level physical engine, 90% vehicle charging efficiency, local battery controller, faults, parking queues, import allowances and export limit. Immediate charging deliberately ignores the import limit as an uncontrolled baseline. Advanced controllers use perfect synthetic building/PV forecasts and rebuild connected-vehicle plans at quarter-hour boundaries and active-set changes. These are heuristics, not proven optimal solutions or live market control.</p><p>Equivalent service requires matching delivery for every vehicle, matching terminal stored energy, and zero import-limit violations in both runs. Even then, always inspect readiness: equal delivery does not imply every requested target was met. CSV and JSON contain the scenario ID, model version, assumptions and all six results.</p></details>
 </div>;
}
