'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Zap,ArrowLeft,Play,Square,Download,BrainCircuit} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {SELECTOR_KEY,objectiveDefaults,strategyIds,selectorScenario,isSelector,type SelectorSettings,type SelectorModel,type SelectorRow,selectorEvaluation} from '../../lib/twin/selector';
import './FlexibilityLab.css';
import './StrategyTrainingLab.css';
type Evaluation=ReturnType<typeof selectorEvaluation>;
const names:Record<string,string>={immediate:'Immediate',balanced:'Load balancing',ems:'Deadline-aware',cheap:'Cheapest',peak:'Peak-aware',total:'Total-cost',learned:'Learned selector',oracle:'Hindsight best (oracle)'};
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function StrategyTrainingLab(){
 const [settings,setSettings]=useState<SelectorSettings>({seed:42,days:365,objective:{...objectiveDefaults}}),[busy,setBusy]=useState(false),[experimentSettings,setExperimentSettings]=useState<SelectorSettings>(),[progress,setProgress]=useState(0),[phase,setPhase]=useState('training'),[benchmarkSeed,setBenchmarkSeed]=useState<number>(),[benchmarkRows,setBenchmarkRows]=useState<SelectorRow[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[latest,setLatest]=useState<SelectorRow>(),[candidates,setCandidates]=useState<{k:number;validationRegret:number;label?:string}[]>([]),[model,setModel]=useState<SelectorModel>(),[rows,setRows]=useState<SelectorRow[]>([]),[evaluation,setEvaluation]=useState<Evaluation>(),[error,setError]=useState(''),[testDay,setTestDay]=useState(0);
 const worker=useRef<Worker|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(SELECTOR_KEY);if(saved){const m=JSON.parse(saved);if(isSelector(m))setModel(m);}}catch{setError('Saved selector could not be read.');}return ()=>worker.current?.terminate();},[]);
 function start(){setExperimentSettings({...settings,objective:{...settings.objective}});worker.current?.terminate();setBusy(true);setProgress(0);setPhase('training');setCounts({});setBenchmarkRows([]);setBenchmarkSeed(undefined);setRows([]);setEvaluation(undefined);setCandidates([]);setError('');const w=new Worker(new URL('../../workers/strategy-selector.worker.ts',import.meta.url),{type:'module'});worker.current=w;
 w.onmessage=e=>{const m=e.data;if(m.type==='progress'){setProgress(m.day);setPhase(m.phase);if(m.phase==='training'){setCounts(m.counts);setLatest(m.last);}}else if(m.type==='candidate')setCandidates(c=>[...c,{k:m.k,validationRegret:m.validationRegret,label:m.label}]);else if(m.type==='frozen'){setModel(m.model);setProgress(0);setPhase('benchmark');}else if(m.type==='complete'){setModel(m.model);setRows(m.rows);setBenchmarkRows(m.benchmarkRows);setBenchmarkSeed(m.benchmarkSeed);setEvaluation(m.evaluation);setTestDay(m.evaluation.predictions[0].day);setBusy(false);try{localStorage.setItem(SELECTOR_KEY,JSON.stringify(m.model));}catch{setError('Training completed; browser storage failed. Export the model to keep it.');}w.terminate();}else if(m.type==='error'){setError(m.message);setBusy(false);w.terminate();}};
 w.onerror=e=>{setError(e.message||'Worker failed');setBusy(false);w.terminate();};w.postMessage(settings);}
 function stop(){worker.current?.terminate();setBusy(false);setError('Training stopped. No incomplete model was saved.');}
 const bestFixed=evaluation?strategyIds.reduce((best,id)=>evaluation.totals[id].score<evaluation.totals[best].score?id:best,strategyIds[0]):undefined;
 const improvement=evaluation&&bestFixed?evaluation.totals[bestFixed].score-evaluation.totals.learned.score:0;
 const chart=strategyIds.map(id=>({name:names[id],wins:counts[id]??0}));
 return <main className="flex-lab"><header className="header"><div className="brand"><div className="brandmark"><Zap size={23} fill="currentColor"/></div><div className="brandname">FUTURE <span>EV</span></div><div className="divider"/><h2>Strategy Learning</h2></div><nav className="header-actions"><Link className="btn" href="/flexibility/"><ArrowLeft size={17}/>Flexibility Lab</Link><Link className="btn" href="/training/"><BrainCircuit size={17}/>Single-teacher ML</Link>{model&&<button className="btn" onClick={()=>download('strategy-selector-v2.json',model)}><Download size={17}/>Export selector</button>}</nav></header><div className="workspace"><div className="intro"><div><p className="eyebrow">SIX STRATEGIES / SUPERVISED LEARNING / HELD-OUT TESTING</p><h1>Learn when each strategy earns its place.</h1><p>Run all six. Score their consequences. Learn the choice before seeing the outcome.</p></div><span className="badge">Synthetic data · browser-local training</span></div>
 <aside className="flex-notice">Illustrative synthetic simulation. This is a cost-sensitive nearest-neighbour strategy model, separate from the existing charging MLP. It estimates each strategy’s objective cost and switches only when justified against a validation-selected fallback. It selects a strategy for a whole scenario; it does not train plug-in availability forecasts or switch strategies during a charging session.</aside>
 <div className="flex-layout"><section className="flex-card flex-controls"><h2>Training experiment</h2><label>Dataset size<select aria-label="Selector dataset size" disabled={busy} value={settings.days} onChange={e=>setSettings(s=>({...s,days:Number(e.target.value)}))}><option value={35}>Quick run · 35 days across four seasons</option><option value={140}>Extended run · 140 days</option><option value={365}>Full synthetic year · 365 days</option></select></label><label>Scenario seed<input aria-label="Selector seed" disabled={busy} type="number" min={0} max={100000} value={settings.seed} onChange={e=>{const seed=Number(e.target.value);if(Number.isInteger(seed)&&seed>=0&&seed<=100000)setSettings(s=>({...s,seed}));}}/></label>
 <h3>Objective weights</h3>{Object.entries(settings.objective).map(([key,value])=><label key={key}>{key==='departureEurPerKwh'?'Unmet departure energy (€/kWh)':key==='unsafeEurPerMinute'?'Import violation (€/minute)':'Excess import (€/kWh)'}<input disabled={busy} aria-label={key} type="number" min={0} max={100000} value={value} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v)&&v>=0&&v<=100000)setSettings(s=>({...s,objective:{...s.objective,[key]:v}}));}}/></label>)}
 <p>Objective = actual energy cost − gross flexibility proceeds + flexibility penalties + fees + departure and safety penalties. These weights are illustrative preferences, not market fines. Monthly peak charges are not added to a daily score.</p>
 <button className="btn primary" disabled={busy} onClick={start}><Play size={17}/>Train across six strategies</button>{busy&&<button className="btn" onClick={stop}><Square size={17}/>Stop training</button>}
 {error&&<p role="alert">{error}</p>}<p>Training runs in a Web Worker. Scenarios vary seasons, regional tariffs, capacity, solar, demand, pool size, participation and unexpected failures. Nothing is uploaded to GitHub.</p>
 <label>Import trained selector<input aria-label="Import selector" type="file" accept=".json" disabled={busy} onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const m=JSON.parse(await f.text());if(!isSelector(m))throw Error('Invalid selector package');setModel(m);setRows([]);setEvaluation(undefined);localStorage.setItem(SELECTOR_KEY,JSON.stringify(m));setError('');}catch(err){setError(String(err));}}}/></label></section>
 <div className="flex-results"><section className="flex-card"><h2>Experiment progress</h2><progress aria-label="Strategy training progress" max={settings.days} value={progress}/><p role="status">{busy?`${phase==='benchmark'?'Fresh-seed benchmark':'Training dataset'} day ${progress} / ${settings.days} · six paired counterfactual runs` : evaluation?`Training complete · ${rows.length} scenarios`:'Ready to generate and train'}</p><div className="flex-metrics"><div><small>Training days</small><b>{model?.trainDays??'—'}</b></div><div><small>Validation days</small><b>{model?.validationDays??'—'}</b></div><div><small>Fresh benchmark days</small><b>{evaluation?.testDays??'—'}</b></div><div><small>Test agreement</small><b>{evaluation?`${(100*evaluation.agreement).toFixed(1)}%`:'—'}</b></div></div><div className="flex-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} layout="vertical" margin={{left:8,right:16,top:5,bottom:5}}><CartesianGrid stroke="#293644"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={95} tick={{fontSize:11}} interval={0}/><Tooltip contentStyle={{background:'var(--popover)',border:'1px solid var(--border)'}}/><Bar dataKey="wins" name="Lowest-score scenarios" fill="#70e3bb" isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p>These are hindsight teacher labels across generated scenarios, including internal held-out rows. Only training rows enter the cost model. Fresh-seed benchmark outcomes never enter fitting or validation. A strategy can have zero winning examples; no diversity or AI improvement is fabricated.</p></section>
 {latest&&<section className="flex-card"><h2>Latest six-strategy evaluation · day {latest.day+1}</h2><p>Whole-week split: {latest.split}. Best scored strategy: {names[latest.winner]}.</p><div className="flex-table"><table><thead><tr><th>Strategy</th><th>Objective ↓</th><th>Unmet departure kWh</th><th>Delivery shortfall kWh</th><th>Unsafe minutes</th></tr></thead><tbody>{latest.outcomes.map(o=><tr key={o.strategy}><th>{names[o.strategy]}</th><td>{o.score.toFixed(2)}</td><td>{o.departureShortfall.toFixed(2)}</td><td>{o.deliveryShortfall.toFixed(2)}</td><td>{o.violationMinutes}</td></tr>)}</tbody></table></div></section>}
 <section className="flex-card"><h2>Validation chooses model complexity</h2><p>Whole weeks stay in one split. Feature scaling and neighbour examples use training days only. Validation selects feature weights, neighbour count, shrinkage and switching margin by mean objective regret. The model is frozen before a separate fresh-seed benchmark is generated. Internal test days are excluded from fitting and tuning.</p><div className="flex-table"><table><thead><tr><th>Improving validation candidate</th><th>Validation regret ↓</th></tr></thead><tbody>{candidates.map((c,i)=><tr key={i}><th>{c.label??c.k}</th><td>{c.validationRegret.toFixed(2)}</td></tr>)}</tbody></table></div>{model&&<p>Selected k = {model.k} · fallback {model.baseline} · switching margin {model.margin>=1e14?'fixed fallback only':model.margin} · model {model.fingerprint}. Stored model has {model.examples.length} training examples. Neighbour label agreement is not a calibrated probability. Costs and a validation-selected fallback drive the decision.</p>}</section>
 {evaluation&&<><section className="flex-card"><h2>Held-out results: AI versus every fixed strategy</h2><p className="selector-verdict">{improvement>0?`Learned selection improves the weighted objective by ${improvement.toFixed(1)} versus the best fixed strategy (${names[bestFixed!]}).`:`Learned selection does not outperform the best fixed strategy (${names[bestFixed!]}): its weighted objective is ${Math.abs(improvement).toFixed(1)} higher.`}</p><p>Independent benchmark seed {benchmarkSeed}: {evaluation.testDays} unseen scenarios. Mean regret: {evaluation.meanRegret.toFixed(2)} objective units per test scenario. The oracle knows all outcomes in hindsight and is an evaluation bound, not a deployable policy. Compare safety and driver service alongside costs.</p><div className="flex-table"><table><thead><tr><th>Policy</th><th>Total objective ↓</th><th>Energy €</th><th>Net flexibility €*</th><th>Departure shortfall kWh</th><th>Delivery shortfall kWh</th><th>Unsafe minutes</th></tr></thead><tbody>{Object.entries(evaluation.totals).map(([id,t])=><tr key={id} className={id==='learned'?'selector-highlight':''}><th>{names[id]}</th><td>{t.score.toFixed(1)}</td><td>{t.energyCost.toFixed(1)}</td><td>{t.netFlexValue.toFixed(1)}</td><td>{t.departureShortfall.toFixed(1)}</td><td>{t.deliveryShortfall.toFixed(1)}</td><td>{t.violationMinutes}</td></tr>)}</tbody></table></div><p>*Net flexibility includes incremental charging cost. Scoring accounts for this once. Pools are identical replicas, not diverse geographic assets.</p><button className="btn" onClick={()=>download('strategy-learning-evidence.json',{settings:experimentSettings,model,rows,benchmarkRows,benchmarkSeed,evaluation})}><Download size={17}/>Export training evidence</button></section>
 <section className="flex-card"><h2>Inspect an unseen scenario</h2><label>Held-out day<select aria-label="Held-out day" value={testDay} onChange={e=>setTestDay(Number(e.target.value))}>{evaluation.predictions.map(p=><option key={p.day} value={p.day}>Day {p.day+1} · selected {names[p.predicted]} · best {names[p.winner]} · regret {p.regret.toFixed(1)}</option>)}</select></label><Link className="btn primary" href="/flexibility/" onClick={()=>{localStorage.setItem('ev-selector-scenario-v1',JSON.stringify(selectorScenario(testDay,benchmarkSeed!)));}}>Replay with learned selection</Link></section>
 <section className="flex-card"><h2>Confusion matrix · hindsight best versus selected</h2><div className="flex-table"><table><thead><tr><th>Best ↓ / selected →</th>{strategyIds.map(id=><th key={id}>{names[id]}</th>)}</tr></thead><tbody>{evaluation.confusion.map(c=><tr key={c.actual}><th>{names[c.actual]}</th>{strategyIds.map(id=><td key={id}>{c[id]}</td>)}</tr>)}</tbody></table></div></section></>}
 </div></div></div></main>;
}
