"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,BrainCircuit,Check,Download,FlaskConical,Play,Save,ShieldCheck,Square,Waypoints} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {defaults,type Config} from '@/lib/twin/engine';
import {advancedPolicies,markets,optimizerDefaults,type OptimizerConfig} from '@/lib/twin/optimizer';
import {YEAR_DAYS,type AnnualSettings,type TeacherPolicy} from '@/lib/twin/annual';
import {annualBacktestCsv,type AnnualBacktestReport} from '@/lib/twin/backtest';
import {FEATURE_NAMES,isNetwork,ML_MODEL_STORAGE_KEY,type FitProgress,type Network,type Sample} from '@/lib/twin/ml';
import './TrainingLab.css';

const SOURCE_KEY='future-ev-energy-twin-ai-ems-training-source-v1';
const RETURN_KEY='future-ev-energy-twin-ai-ems-training-return-v1';
type Source={config:Config;optimizer:OptimizerConfig;advanced:boolean};
type Message={type:'progress';phase:'backtest';day:number;total:number;rows:number;season:string}|({type:'epoch'}&FitProgress)|{type:'backtest-complete';report:AnnualBacktestReport;samples:Sample[]}|{type:'fit-complete';model:Network}|{type:'error';message:string};
const fallback:Source={config:defaults,optimizer:optimizerDefaults,advanced:false};
const policies:TeacherPolicy[]=['immediate','balanced','ems','cheap','peak','total'];
const names:Record<TeacherPolicy,string>={immediate:'Immediate charging',balanced:'Load balancing',ems:'Deadline-aware EMS',cheap:'Cheapest energy',peak:'Peak-aware',total:'Total-cost-aware'};
const fmt=(n:number,d=2)=>n.toLocaleString('en-GB',{maximumFractionDigits:d,minimumFractionDigits:d});
const percent=(n:number)=>`${(n*100).toFixed(1)}%`;
function dateLabel(day:number){return new Date(Date.UTC(2025,0,day)).toLocaleDateString('en-GB',{month:'short',day:'2-digit',timeZone:'UTC'});}
function download(name:string,content:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function monthCounts(samples:Sample[]){const values=new Array(12).fill(0);for(const s of samples)values[new Date(Date.UTC(2025,0,s.day+1)).getUTCMonth()]++;return values.map((rows,i)=>({month:new Date(Date.UTC(2025,i,1)).toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'}),rows}));}
function featureInfluence(model:Network){return FEATURE_NAMES.map((name,i)=>{let influence=0;for(let j=0;j<model.hiddenUnits;j++)influence+=Math.abs(model.weightsInputHidden[i*model.hiddenUnits+j]*model.weightsHiddenOutput[j]);return {name:name.replaceAll('_',' '),value:influence};}).sort((a,b)=>b.value-a.value).slice(0,9);}

export default function TrainingLab(){
 const [source,setSource]=useState<Source>(fallback),[teacher,setTeacher]=useState<TeacherPolicy>('ems'),[epochs,setEpochs]=useState(32),[seed,setSeed]=useState(defaults.seed);
 const [busy,setBusy]=useState(false),[phase,setPhase]=useState<'idle'|'backtest'|'fit'>('idle'),[dayProgress,setDayProgress]=useState({day:0,rows:0,season:'Winter'}),[history,setHistory]=useState<FitProgress[]>([]),[model,setModel]=useState<Network|null>(null),[samples,setSamples]=useState<Sample[]>([]),[report,setReport]=useState<AnnualBacktestReport|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const workerRef=useRef<Worker|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(SOURCE_KEY);if(raw){const parsed=JSON.parse(raw) as Source;if(parsed.config&&parsed.optimizer){setSource(parsed);setTeacher(parsed.advanced?parsed.optimizer.policy:parsed.config.policy);setSeed(parsed.config.seed);}}const saved=localStorage.getItem(ML_MODEL_STORAGE_KEY);if(saved){const parsed=JSON.parse(saved);if(isNetwork(parsed))setModel(parsed);}}catch{setError('A saved local model or scenario could not be read.');}return()=>workerRef.current?.terminate();},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 const dataSplits=useMemo(()=>({train:samples.filter(s=>s.split==='train').length,validation:samples.filter(s=>s.split==='validation').length,test:samples.filter(s=>s.split==='test').length}),[samples]);
 const progressPct=busy?phase==='fit'?90+Math.round((history.at(-1)?.epoch??0)/epochs*10):Math.round(dayProgress.day/YEAR_DAYS*90):model?100:report?90:0;
 const settings=():AnnualSettings=>({config:source.config,optimizer:source.optimizer,teacherPolicy:teacher,seed});
 const makeWorker=()=>{
  const worker=new Worker(new URL('../../workers/ml-training.worker.ts',import.meta.url),{type:'module'});workerRef.current=worker;
  worker.onmessage=(event:MessageEvent<Message>)=>{
   const msg=event.data;
   if(msg.type==='progress'){setPhase('backtest');setDayProgress({day:msg.day,rows:msg.rows,season:msg.season});return;}
   if(msg.type==='epoch'){setPhase('fit');setHistory(v=>[...v,msg]);return;}
   if(msg.type==='error'){setError(msg.message);setBusy(false);setPhase('idle');worker.terminate();workerRef.current=null;return;}
   if(msg.type==='backtest-complete'){setReport(msg.report);setSamples(msg.samples);setBusy(false);setPhase('idle');worker.terminate();workerRef.current=null;setNotice('Year backtest complete. Review the six strategy results, then train on the held-out weekly splits.');return;}
   if(msg.type==='fit-complete'){setModel(msg.model);setBusy(false);setPhase('idle');worker.terminate();workerRef.current=null;try{localStorage.setItem(ML_MODEL_STORAGE_KEY,JSON.stringify(msg.model));setNotice('Model trained on this backtest, scored on held-out weeks, and saved in this browser.');}catch{setNotice('Model trained. Browser storage is full; download the model package to keep it.');}}
  };
  worker.onerror=event=>{setError(event.message||'The browser worker stopped unexpectedly.');setBusy(false);setPhase('idle');worker.terminate();workerRef.current=null;};
  return worker;
 };
 const start=()=>{
  if(busy)return;setBusy(true);setPhase('backtest');setError('');setNotice('');setHistory([]);setSamples([]);setReport(null);setDayProgress({day:0,rows:0,season:'Winter'});
  setModel(null);try{localStorage.removeItem(ML_MODEL_STORAGE_KEY);}catch{}
  makeWorker().postMessage({type:'backtest',settings:settings()});
 };
 const train=()=>{
  if(busy||!report||!samples.length)return;setBusy(true);setPhase('fit');setError('');setNotice('');setHistory([]);
  makeWorker().postMessage({type:'fit',settings:settings(),samples,datasetFingerprint:report.datasetFingerprint,days:report.days,epochs,seed});
 };
 const resetSetup=()=>{setReport(null);setSamples([]);setModel(null);setHistory([]);try{localStorage.removeItem(ML_MODEL_STORAGE_KEY);}catch{}setNotice('Backtest cleared. Update the setup and run a new year.');};
 const cancel=()=>{workerRef.current?.terminate();workerRef.current=null;setBusy(false);setPhase('idle');setNotice(phase==='backtest'?'Backtest stopped. No partial annual report or model was saved.':'Training stopped. The completed backtest stays in this page.');};
 const saveModel=()=>{if(!model)return;try{localStorage.setItem(ML_MODEL_STORAGE_KEY,JSON.stringify(model));setNotice('Trained model saved for the Energy Twin in this browser.');}catch{setError('Browser storage is full. Download the model package instead.');}};
 const importModel=async(event:React.ChangeEvent<HTMLInputElement>)=>{try{const file=event.target.files?.[0];if(!file)return;const next=JSON.parse(await file.text());if(!isNetwork(next))throw new Error('The file is not a compatible Energy Twin compact model package.');localStorage.setItem(ML_MODEL_STORAGE_KEY,JSON.stringify(next));setModel(next);setNotice('Model package imported and made available to the Energy Twin.');}catch(e){setError(e instanceof Error?e.message:'Could not import model package.');}event.target.value='';};
 const returnToTwin=()=>{try{localStorage.setItem(RETURN_KEY,JSON.stringify({schemaVersion:2,...source}));}catch{}};
 const chart=history.map(p=>({epoch:p.epoch,train:p.trainMse,validation:p.validationMse}));
 const exportAnnual=()=>report&&download('ems-annual-backtest-results.csv',annualBacktestCsv(report),'text/csv;charset=utf-8');
 const monthly=useMemo(()=>monthCounts(samples),[samples]);
 const influence=useMemo(()=>model?featureInfluence(model):[],[model]);
 return <div className="training-shell">
  <header className="header training-header"><div className="brand"><div className="brandmark"><BrainCircuit size={23}/></div><div className="brandname">FUTURE <span>EV</span></div><div className="divider"/><h2>Annual backtest &amp; ML</h2></div><div className="header-actions"><span className="badge training-badge">ILLUSTRATIVE · SYNTHETIC ONLY</span><Link className="btn" href="/" onClick={returnToTwin}><ArrowLeft/>Return to Energy Twin</Link><Link className="btn" href="/strategy-training/">Six-strategy learning</Link></div></header>
  <main className="training-workspace">
   <div className="training-hero"><div><div className="eyebrow">SIMULATION DATA → LEARNED POLICY → ENERGY TWIN</div><h1>Backtest one synthetic year, then train.</h1><p>Generate and backtest a synthetic year in this browser, train on earlier weeks, inspect held-out results, then apply the trained policy to the Energy Twin’s current DES.</p></div><div className="illustrative-stamp"><FlaskConical/><span>Sandbox experiment<br/><b>No live data or control</b></span></div></div>
   <div className="synthetic-warning" role="note"><ShieldCheck/><div><b>Illustrative results from synthetic data</b><p>The year, arrival patterns, tariffs, weather and outcomes are generated by this simulator. The model demonstrates an ML workflow; it is not trained or validated on real sites, drivers, supplier prices or grid telemetry.</p></div></div>
   <section className="training-flow" aria-label="Backtest, train, and apply workflow">
    <div className="training-flow-heading"><div><span className="eyebrow">THE WORKFLOW</span><h2>Backtest first. Train second. Apply last.</h2></div><span className="training-flow-local">Runs in this browser</span></div>
    <div className="training-flow-steps">
     <article><span className="training-flow-number">01</span><b>Generate the twin year</b><p>Build 365 synthetic days and charging examples from the selected site settings, weather, arrivals, tariffs and teacher policy.</p><small>{report?`${report.days} days complete`:busy&&phase==='backtest'?'Backtest running now':'Start here · data stays in this page'}</small></article>
     <article><span className="training-flow-number">02</span><b>Train on past weeks</b><p>Fit the small policy using training weeks from that generated year. Whole weeks stay together in each split.</p><small>{model?'Complete · trained from this backtest':report?'Ready to train':'Locked until backtest completes'}</small></article>
     <article><span className="training-flow-number">03</span><b>Check held-out weeks</b><p>Validation and test weeks are kept out of fitting. Review prediction error and charge/pause agreement before applying.</p><small>{model?'Complete · held-out results available':report?'Waiting for model training':'Locked until model fit'}</small></article>
     <article><span className="training-flow-number">04</span><b>Apply in the current DES</b><p>Return to the Energy Twin and compare the saved policy in its current discrete-event simulation.</p><small>{model?'Ready · model saved in this browser':'Locked until training completes'}</small></article>
    </div>
    <p className="training-flow-storage">GitHub Actions only checks and publishes this page’s code. The generated year and training data are not uploaded to GitHub; export the CSV or model yourself if you want a file.</p>
   </section>
   {notice&&<div className="notice" role="status">{notice}</div>}{error&&<div className="training-error" role="alert">{error}</div>}
   <div className="training-top-grid">
    <section className="panel training-controls"><div className="panel-head"><h2>Experiment design</h2><span className="badge">365-day profile</span></div><div className="panel-body">
     <label className="training-field"><span>Teacher policy to imitate</span><select value={teacher} disabled={busy||!!report} onChange={e=>setTeacher(e.target.value as TeacherPolicy)}>{policies.map(p=><option key={p} value={p}>{names[p]}</option>)}</select><small>The simulator supplies example charging actions. The model learns a compact approximation of that policy.</small></label>
     <label className="training-field"><span>Tariff region</span><select value={source.optimizer.market} disabled={busy||!!report} onChange={e=>setSource(s=>({...s,optimizer:{...s.optimizer,market:e.target.value as OptimizerConfig['market']}}))}>{markets.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
     <div className="training-knobs"><label><span>Training passes</span><select value={epochs} onChange={e=>setEpochs(Number(e.target.value))}>{[16,24,32,48].map(n=><option key={n} value={n}>{n} epochs</option>)}</select></label><label><span>Random seed</span><input type="number" min="0" max="999999" value={seed} disabled={busy||!!report} onChange={e=>setSeed(Math.max(0,Number(e.target.value)||0))}/></label></div>
     <div className="training-source"><div className="training-source-head"><Waypoints/><b>Inherited from the Energy Twin</b></div><div className="source-chips"><span>{source.config.grid} kW grid</span><span>{source.config.solar} kWp solar</span><span>{fmt(source.config.demand,2)}× building demand</span><span>{source.config.chargers} charge points</span><span>{source.config.battery?'Stationary battery on':'Stationary battery off'}</span><span>{source.config.flexible?'Flexible loads on':'Flexible loads off'}</span><span>{markets.find(m=>m.id===source.optimizer.market)?.name}</span><span>{source.optimizer.peak} kW target</span></div><small>Daily arrivals, vehicle classes, energy requests, arrival SoC, departure deadlines, queueing, faults and charging physics come from the shared simulator. Random seeds change visits across the year.</small></div>
     <div className="training-actions"><button className="btn primary" disabled={busy} onClick={start}><Play fill="currentColor"/>{report?"Run a new 365-day backtest":"Run 365-day backtest"}</button><button className="btn" disabled={busy||!report||!samples.length||!!model} onClick={train}><BrainCircuit/>Train on this backtest</button>{report&&!busy&&<button className="btn" onClick={resetSetup}>Change setup</button>}{busy&&<button className="btn" onClick={cancel}><Square/>Stop</button>}</div><small className="worker-note">Backtest and fitting run separately in a browser worker. No data or model is sent to a server.</small>
    </div></section>
    <section className="panel training-progress-panel"><div className="panel-head"><div><h2>Training progress</h2><small>{busy?phase==='fit'?'Fitting the compact neural policy from the completed backtest': 'Running the annual strategy backtest':model?`Saved model · trained ${new Date(model.createdAt).toLocaleString()}`:report?'Backtest ready · train when you are':'Ready when you are'}</small></div><BrainCircuit color="#70e3bb"/></div><div className="training-progress-body">
     <div className="progress-label"><span>{busy?phase==='fit'?`Fitting policy · epoch ${history.at(-1)?.epoch??0} of ${epochs}`:`${dayProgress.season} · day ${dayProgress.day} of ${YEAR_DAYS} · ${dayProgress.rows.toLocaleString()} examples`:model?'Model package ready':report?'Annual backtest complete · ready to train':'Waiting for the annual backtest'}</span><b>{progressPct}%</b></div><div className="progress-track"><i style={{width:`${progressPct}%`}}/></div><div className="training-kpis"><div><small>Days simulated</small><b>{busy&&phase==='backtest'?dayProgress.day:report?.days??model?.days??0}<em> / 365</em></b></div><div><small>Decision examples</small><b>{(busy&&phase==='backtest'?dayProgress.rows:report?.rows??model?.rowCount??0).toLocaleString()}</b></div><div><small>Network</small><b>17 → 10 → 1</b></div></div>
     <div className="loss-chart-title"><b>Learning curve</b><small>Normalized action error · lower is better</small></div><div className="loss-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid stroke="#263844" vertical={false}/><XAxis dataKey="epoch" tickLine={false} axisLine={false}/><YAxis width={42} tickLine={false} axisLine={false} domain={[0,'auto']}/><Tooltip contentStyle={{background:'#14232f',border:'1px solid #3a5060'}}/><Line isAnimationActive={false} type="monotone" dataKey="train" name="Training MSE" stroke="#70e3bb" dot={false}/><Line isAnimationActive={false} type="monotone" dataKey="validation" name="Validation MSE" stroke="#f6c66b" dot={false}/></LineChart></ResponsiveContainer>{!history.length&&<div className="chart-empty">The live training and validation error will draw here.</div>}</div>
     {model&&<div className="model-eval-grid"><div><small>Holdout test error</small><b>{fmt(model.metrics.testMae*100,1)}% AC-power MAE</b></div><div><small>Charge / pause agreement</small><b>{percent(model.metrics.testActionAgreement)}</b></div><div><small>Test date blocks</small><b>{model.testRows.toLocaleString()} samples</b></div><div><small>Model footprint</small><b>{(JSON.stringify(model).length/1024).toFixed(1)} KB</b></div></div>}
    </div></section>
   </div>
   {report&&<section className="panel annual-report-panel"><div className="panel-head"><div><h2>One synthetic year · six no-ML strategies</h2><small>{report.days} simulated days · {report.rows.toLocaleString()} training examples · synthetic tariffs in EUR</small></div><button className="btn" onClick={exportAnnual}><Download/>Export results CSV</button></div><div className="annual-report-note"><ShieldCheck size={16}/><span>Illustrative backtest only. Costs use the simulator’s synthetic tariff and exclude VAT. Capacity cost is an annualized sensitivity only when a rate is configured; it is added to the total modeled cost. Peak is the highest simulated day in the year; this is not a supplier bill or live-site forecast.</span></div><div className="annual-table-wrap"><table className="annual-table"><thead><tr><th>Strategy</th><th>Net energy cost</th><th>Capacity cost / year</th><th>Total modeled cost</th><th>Energy delivered</th><th>Departure ready</th><th>Grid violations</th><th>Max 15-min peak</th></tr></thead><tbody>{report.results.map(r=><tr key={r.id} className={r.id==='balanced'?'annual-reference':''}><td><b>{r.name}</b>{r.id==='balanced'&&<small>Reference</small>}</td><td>{'€'+fmt(r.energyCost)}</td><td>{r.capacityCostEur===null?'Not set':'€'+fmt(r.capacityCostEur)}</td><td>{'€'+fmt(r.totalCost)}</td><td>{fmt(r.deliveredKwh,0)} / {fmt(r.requestedKwh,0)} kWh</td><td>{r.ready.toLocaleString()} / {r.departed.toLocaleString()} ({fmt(r.readinessPct,1)}%)</td><td>{r.violationMinutes.toLocaleString()} min · {fmt(r.excessKwh,1)} kWh</td><td>{fmt(r.quarterPeakKw,1)} kW</td></tr>)}</tbody></table></div><div className="annual-split-summary"><span>Training <b>{report.splitCounts.train.toLocaleString()}</b></span><span>Validation <b>{report.splitCounts.validation.toLocaleString()}</b></span><span>Held-out test <b>{report.splitCounts.test.toLocaleString()}</b></span><span>Dataset fingerprint <b>{report.datasetFingerprint}</b></span></div><p className="split-explainer">The financial and energy table compares the six rule-based strategies across the generated year. The selected teacher’s vehicle decisions from this same year feed the model; entire weeks are kept in one training, validation or test split.</p></section>}
   <div className="training-lower-grid">
    <section className="panel"><div className="panel-head"><div><h2>One synthetic year, all seasons</h2><small>15-minute decision snapshots · same vehicle and battery mechanics</small></div><span className="badge">365 days</span></div><div className="month-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthly}><CartesianGrid stroke="#263844" vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis width={44} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'#14232f',border:'1px solid #3a5060'}}/><Area isAnimationActive={false} type="monotone" dataKey="rows" name="Vehicle decision samples" stroke="#91a7fc" fill="#91a7fc25"/></AreaChart></ResponsiveContainer>{!samples.length&&<div className="chart-empty">Monthly examples appear as the annual simulator run is collected.</div>}</div><div className="split-pills"><span><i className="split-train"/>Training <b>{dataSplits.train.toLocaleString()}</b></span><span><i className="split-validation"/>Validation <b>{dataSplits.validation.toLocaleString()}</b></span><span><i className="split-test"/>Test <b>{dataSplits.test.toLocaleString()}</b></span></div><p className="split-explainer">Entire week blocks are assigned to one split, so a day’s rows cannot leak across training and test. Synthetic faults, restricted-grid days, fleet patterns, cloudy profiles and seasonal temperature/daylight variation are included.</p></section>
    <section className="panel"><div className="panel-head"><div><h2>What shaped the policy?</h2><small>Relative input influence estimate · not causal importance</small></div></div><div className="influence-list">{model?influence.map((f,i)=><div className="influence-row" key={f.name}><span>{f.name}</span><div><i style={{width:`${Math.max(3,f.value/(influence[0]?.value||1)*100)}%`,opacity:1-i*.06}}/></div><b>{i+1}</b></div>):<div className="empty">Train a model to inspect the learned weights.</div>}</div><div className="feature-tags">{FEATURE_NAMES.map(name=><span key={name}>{name.replaceAll('_',' ')}</span>)}</div></section>
   </div>
   <section className="panel model-package-panel"><div className="panel-head"><div><h2>Model package & handoff</h2><small>Compact, local and reloadable from the main Energy Twin</small></div><span className={`badge ${model?'green':'training-badge'}`}>{model?'READY':'NO TRAINED MODEL'}</span></div><div className="model-package-body"><div className="model-package-copy"><p>The model predicts a vehicle’s requested charging power from time of day, season, weather, tariff, site headroom, battery state, driver group, state of charge, remaining energy and departure slack. The simulator’s deterministic plant still clamps every learned request to physical charger and site limits.</p>{model&&<div className="model-meta"><span>Teacher · <b>{names[model.teacherPolicy as TeacherPolicy]}</b></span><span>Tariff · <b>{markets.find(m=>m.id===model.market)?.name}</b></span><span>Grouped split · <b>{model.trainRows.toLocaleString()} / {model.validationRows.toLocaleString()} / {model.testRows.toLocaleString()}</b></span><span>Dataset fingerprint · <b>{model.datasetFingerprint}</b></span></div>}</div><div className="model-package-actions"><button className="btn" disabled={!model} onClick={saveModel}><Save/>Save local model</button><button className="btn" disabled={!model} onClick={()=>model&&download('ems-synthetic-trained-model.json',JSON.stringify(model,null,2),'application/json')}><Download/>Export model</button><button className="btn" disabled={!samples.length} onClick={()=>download('ems-synthetic-year-training-data.csv',annualDatasetCsv(samples),'text/csv;charset=utf-8')}><Download/>Export dataset CSV</button><button className="btn" onClick={()=>fileRef.current?.click()}><Download/>Import model</button><input ref={fileRef} hidden type="file" accept=".json,application/json" onChange={importModel}/><Link className={model?"btn primary":"btn"} aria-disabled={!model} href={model?"/":"#model-package"} onClick={e=>{if(!model){e.preventDefault();setNotice("Run the backtest and train a model before applying ML in the current DES.");}else returnToTwin();}}><Check/>{model?"Apply in current DES":"Train first to enable DES handoff"}</Link></div></div></section>
   <footer className="footer"><span>EMS ML TRAINING LAB</span><span>Synthetic data only · compact neural policy · local browser training</span></footer>
  </main>
 </div>;
}

function annualDatasetCsv(samples:Sample[]){const fields=['day','week','split','scenario','driverKind',...FEATURE_NAMES,'teacherPowerRatio'];const q=(x:unknown)=>`"${String(x??'').replaceAll('"','""')}"`;return [fields,...samples.map(s=>[s.day+1,s.week,s.split,s.scenario,s.vehicleKind,...s.x,s.y])].map(r=>r.map(q).join(',')).join('\n');}
